#:import GameBoard game.gui.board.GameBoard
#:import EmptyHexagon game.gui.board.EmptyHexagon
#:import board_module game.gui.board


<EmptyHexagon>:
    source: 'static/hexagon_empty.png'
    size_hint: None, None
    size: board_module.HEX_WIDTH, board_module.HEX_HEIGHT
    #opacity: 0.1

<GameBoard>:
    canvas:
        Color:
            rgb: 0.9, 0.9, 0.9
        Rectangle:
            pos: self.pos
            size: self.size
